# Generated by Django 3.2.7 on 2021-12-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
