# Generated by Django 4.1.4 on 2023-01-30 15:05

from django.db import migrations, models
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_doctor_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="ghana_card",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=user_profile.models.upload_ghanacard_path,
            ),
        ),
    ]
