# Generated by Django 4.1.4 on 2023-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_personalinfo_ghana_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="profile_complete",
            field=models.BooleanField(default=False),
        ),
    ]
